spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/confirmingAuth
    username: root
    password: Rootroot@1045


  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql:
        dialect: org.hibernate.dialect.MySQL8Dialect

  sql:
    init:
      continue-on-error: true


server:
  port: 8086
